In [2]:
import numpy as np

In [5]:
arr = np.arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
arr[5]

5

In [10]:
arr[3:-2]

array([3, 4, 5, 6, 7, 8])

In [11]:
arr[4:8]=99

In [12]:
arr

array([ 0,  1,  2,  3, 99, 99, 99, 99,  8,  9, 10])

In [14]:
arr_copy = arr.copy()

In [18]:
arr_copy[:] = 100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([ 0,  1,  2,  3, 99, 99, 99, 99,  8,  9, 10])

In [41]:
arr_2d=np.array([[2,3,4, 6],[4,3,5, 2],[5,6,2,0]])

In [42]:
arr_2d

array([[2, 3, 4, 6],
       [4, 3, 5, 2],
       [5, 6, 2, 0]])

In [43]:
arr_2d[0,1]

3

In [45]:
arr_2d[1:,:2]

array([[4, 3],
       [5, 6]])

In [48]:
arr = np.arange(1,10)

In [50]:
arr


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
bool_arr = arr<6

In [54]:
bool_arr

array([ True,  True,  True,  True,  True, False, False, False, False], dtype=bool)

In [56]:
arr[bool_arr] #shows only true value


array([1, 2, 3, 4, 5])

In [58]:
arr[arr>4]

array([5, 6, 7, 8, 9])

In [59]:
arr_2d = np.arange(50).reshape(5,10)

In [60]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
arr_2d[arr_2d>7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [66]:
arr_2d[2:4,7:9]

array([[27, 28],
       [37, 38]])